### ISSUE TITLE
broken link to readme.md file in grav theme page...

### ISSUE THREAD

**Issue by 4evermaat** [geschke/grav-theme-tikva#4]
https://github.com/geschke/grav-theme-tikva/blob/develop/README.md

should be 

**https://github.com/geschke/grav-theme-tikva/#tikva** or 
https://github.com/geschke/grav-theme-tikva/blob/master/README.md

![tikva grav theme broken link in theme settings page](https://cloud.githubusercontent.com/assets/830306/23446305/b549871e-fe74-11e6-9ce3-802f96af8cae.gif)

Minor bug

**Comment by geschke** [comment]
I agree, this was a bug in the released version, it is fixed in the current master branch, but I didn't want to create an extra release for that. ;-)
