### ISSUE TITLE
subfooter needs custom font sizing....

### ISSUE THREAD

**Issue by 4evermaat** [geschke/grav-theme-tikva#6]
I noticed there is no toolbar button for font. Any ideas if I want to make some of the sub-footer text really small?

What about the background of the sub footer.  Is it supposed to be the same as the footer?  Don't see in the theme settings where to customize the sub-footer background.  Only the text within it.

**Comment by geschke** [comment]
The subfooter text is customizable by an edit field - you can use every font size you want, e.g. with 


    <small>smaller text</small>

The color settings - maybe I will add some options to customize them, thanks for your comment!

**Comment by geschke** [comment]
Color settings added.
