### ISSUE TITLE
How can i do submenu ?

### ISSUE THREAD

**Issue by SoDimicom** [geschke/grav-theme-tikva#9]
Could you tell me how to add a submenu in the navbar ?

Like in your site with :
**- Features
    - Flexible Footer
    - Predefined Themes
    - Miscellaneous Settings**

![capture](https://cloud.githubusercontent.com/assets/7480045/23668767/507ccab0-0362-11e7-9b78-dfccab5aba4c.PNG)

Thanks

**Comment by geschke** [comment]
At first, switch "Dropdown in menu" to "enabled". 
Then create a page structure like this:

![bildschirmfoto 2017-03-07 um 18 20 37](https://cloud.githubusercontent.com/assets/272754/23668947/f643728c-0362-11e7-8cd7-cebdc24cec0f.png)

See the page legend for page types - "Features" is a folder, non-routable, visible and published. The pages below (e.g. "Flexible Footer" have the type page, are routable, visible and published. 

That's all. You see a screenshot from the demo site where I've created this structure. 

Kind regards,
   Ralf

**Comment by SoDimicom** [comment]
Thanks ! it's done

**Comment by SoDimicom** [comment]
Last question :), If want to move the text of my navbar in the center it's possible or more right ? because it's too in left for me.

This is my menu : 

![capture2](https://cloud.githubusercontent.com/assets/7480045/23669981/748543ca-0366-11e7-9bd2-1a0060898876.PNG)

from "Home" i want to move on center or more right.

**Comment by geschke** [comment]
I'm sorry, but with the current version it's not possible. It is the default menu of Bootstrap, so at the moment there is no support to move the navigation. 
But it's a good idea so implement this in a later version, maybe to move it to the right or add another option. Thanks for your report!

**Comment by SoDimicom** [comment]
Yes good Idea ! thanks for your time
